name: New Experience
description: Upload a new Expirience to the Gallery
labels: ["experience"]
body:
  - type: markdown
    attributes:
      value: |
        > 1. Create a **new space** which includes _only_ the types, relations, widgets, templates, and objects you want to share. This will avoid accidental sharing of sensitive data from your primary space. Please note: the name and icon of this new space will be displayed for everyone who will install your ANY experience.
        > 2. When the space is ready, export it in Any-Block JSON format. Click on the space name in the top-left corner, click “Export Space”, choose “Any-Block” option and set up following export settings:
        >     - File format – JSON,
        >     - Turn on “Zip archive”
        >     - Turn on “Include files”
        > 3. Make one or several screenshots which show important features of your ANY experience. Save these screenshots in .png format.
        > 4. Fill the form below.
        > 5. Someone from Open Any Team will review your submission, and, when approved, the experience will be published in the [Gallery](https://gallery.any.coop/). You will be recognized as a contributor in our [Github](https://github.com/anyproto/contributors) and on our [website](https://anytype.io/contributors).
  - type: textarea
    id: experience
    attributes:
      label: Experience
      description: Please attach the Experience as a zip archive. It should contain Any-Block JSON files.
      placeholder: |
        New_Experience.zip
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: The Experience title will be displayed in the Gallery.
      placeholder: "(Maximum length of 40 characters)"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please attach one or more screenshots of the Experience. They will be displayed in the Gallery.
      placeholder: |
        Screenshot1.png
        Screenshot2.png
        ...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: It helps people understand what the Experience provides. It will be displayed in the Gallery.
      placeholder: "(Maximum length of 260 characters)"
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: Categories
      description: Select one or more categories that best describe the Experience. It will help people find it in the Gallery.
      multiple: true
      options:
        - Collaboration
        - Dashboard
        - Work
        - Education
        - Personal Growth
        - Project tracking
        - Collection
        - Health & Fitness
        - Finance
        - Food & Nutrition
        - Travel
        - Hobbies
        - Home
        - Other
      default: 12
    validations:
      required: true
  - type: dropdown
    id: language
    validations:
      required: true
    attributes:
      label: Language
      default: 61
      options:
        - ach-UG
        - aa-ER
        - af-ZA
        - ak-GH
        - tw-TW
        - sq-AL
        - am-ET
        - ar-SA
        - ar-BH
        - ar-EG
        - ar-YE
        - an-ES
        - hy-AM
        - frp-IT
        - as-IN
        - ast-ES
        - tay-TW
        - av-DA
        - ae-IR
        - ay-BO
        - az-AZ
        - ban-ID
        - bal-BA
        - bm-ML
        - ba-RU
        - eu-ES
        - be-BY
        - bn-BD
        - bn-IN
        - ber-DZ
        - bh-IN
        - bfo-BF
        - bi-VU
        - bs-BA
        - br-FR
        - bg-BG
        - my-MM
        - ca-ES
        - ceb-PH
        - ch-GU
        - ce-CE
        - chr-US
        - ny-MW
        - zh-CN
        - zh-TW
        - zh-HK
        - zh-MO
        - zh-SG
        - cv-CU
        - kw-GB
        - co-FR
        - cr-NT
        - hr-HR
        - cs-CZ
        - da-DK
        - fa-AF
        - dv-MV
        - nl-NL
        - nl-BE
        - nl-SR
        - dz-BT
        - en-US
        - en-UD
        - en-AR
        - en-AU
        - en-BZ
        - en-CA
        - en-CB
        - en-CN
        - en-DK
        - en-HK
        - en-IN
        - en-ID
        - en-IE
        - en-JM
        - en-JA
        - en-MY
        - en-NZ
        - en-NO
        - en-PH
        - en-PR
        - en-SG
        - en-ZA
        - en-SE
        - en-GB
        - en-ZW
        - eo-UY
        - et-EE
        - ee-GH
        - fo-FO
        - fj-FJ
        - fil-PH
        - fi-FI
        - vls-BE
        - fra-DE
        - fr-FR
        - fr-BE
        - fr-CA
        - fr-LU
        - fr-QC
        - fr-CH
        - fy-NL
        - fur-IT
        - ff-ZA
        - gaa-GH
        - gl-ES
        - ka-GE
        - de-DE
        - de-AT
        - de-BE
        - de-LI
        - de-LU
        - de-CH
        - got-DE
        - el-GR
        - el-CY
        - kl-GL
        - gn-PY
        - gu-IN
        - ht-HT
        - ha-HG
        - haw-US
        - he-IL
        - hz-NA
        - hil-PH
        - hi-IN
        - ho-PG
        - hmn-CN
        - hu-HU
        - is-IS
        - io-EN
        - ig-NG
        - ilo-PH
        - id-ID
        - iu-NU
        - ga-IE
        - it-IT
        - it-CH
        - ja-JP
        - jv-ID
        - quc-GT
        - kab-KAB
        - kn-IN
        - pam-PH
        - ks-IN
        - ks-PK
        - csb-PL
        - kk-KZ
        - km-KH
        - rw-RW
        - tlh-AA
        - kv-KO
        - kg-CG
        - kok-IN
        - ko-KR
        - ku-TR
        - kmr-TR
        - kj-AO
        - ky-KG
        - lol-US
        - lo-LA
        - la-LA
        - lv-LV
        - lij-IT
        - li-LI
        - ln-CD
        - lt-LT
        - jbo-EN
        - nds-DE
        - dsb-DE
        - lg-UG
        - luy-KE
        - lb-LU
        - mk-MK
        - mai-IN
        - mg-MG
        - ms-MY
        - ms-BN
        - ml-IN
        - mt-MT
        - gv-IM
        - mi-NZ
        - arn-CL
        - mr-IN
        - mh-MH
        - moh-CA
        - mn-MN
        - sr-Cyrl-ME
        - me-ME
        - mos-MOS
        - na-NR
        - ng-NA
        - ne-NP
        - ne-IN
        - pcm-NG
        - se-NO
        - ns-ZA
        - no-NO
        - nb-NO
        - nn-NO
        - oc-FR
        - or-IN
        - oj-CA
        - om-ET
        - os-SE
        - pi-IN
        - pap-PAP
        - ps-AF
        - fa-IR
        - en-PT
        - pl-PL
        - pt-PT
        - pt-BR
        - pa-IN
        - pa-PK
        - qu-PE
        - qya-AA
        - ro-RO
        - rm-CH
        - rn-BI
        - ru-RU
        - ru-BY
        - ru-MD
        - ry-UA
        - ru-UA
        - sah-SAH
        - sg-CF
        - sa-IN
        - sat-IN
        - sc-IT
        - sco-GB
        - gd-GB
        - sr-SP
        - sr-CS
        - sh-HR
        - crs-SC
        - sn-ZW
        - ii-CN
        - sd-PK
        - si-LK
        - sk-SK
        - sl-SI
        - so-SO
        - son-ZA
        - ckb-IR
        - nr-ZA
        - sma-NO
        - st-ZA
        - es-ES
        - es-EM
        - es-AR
        - es-BO
        - es-CL
        - es-CO
        - es-CR
        - es-DO
        - es-EC
        - es-SV
        - es-GT
        - es-HN
        - es-419
        - es-MX
        - es-NI
        - es-PA
        - es-PY
        - es-PE
        - es-PR
        - es-US
        - es-UY
        - es-VE
        - su-ID
        - sw-KE
        - sw-TZ
        - ss-ZA
        - sv-SE
        - sv-FI
        - syc-SY
        - tl-PH
        - ty-PF
        - tg-TJ
        - tzl-TZL
        - ta-IN
        - tt-RU
        - te-IN
        - kdh-KDH
        - th-TH
        - bo-BT
        - ti-ER
        - ts-ZA
        - tn-ZA
        - tr-TR
        - tr-CY
        - tk-TM
        - uk-UA
        - hsb-DE
        - ur-IN
        - ur-PK
        - ug-CN
        - uz-UZ
        - val-ES
        - ve-ZA
        - vec-IT
        - vi-VN
        - wa-BE
        - cy-GB
        - wo-SN
        - xh-ZA
        - yi-DE
        - yo-NG
        - zea-ZEA
        - zu-ZA
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: You are contributing this Experience under the terms of the [MIT License](https://github.com/anyproto/gallery/blob/main/LICENSE.md).
      options:
      - label: I agree that this Experience is licensed under the MIT License.
        required: true
      - label: I have intellectual property rights and/or permission to contribute the Experience and its content.
        required: true
      - label: I confirm that the Experience does not contain any harmful or malicious content.
        required: true
